# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=de.vantrex
archives_base_name=skysens
# Dependencies
# check this on https://modmuss50.me/fabric.html


# check these on https://modmuss50.me/fabric.html


minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.12

# Fabric API
fabric_api_version=0.153.0+26.1.2
fabric_version=0.153.0+26.1.2
fabric_language_kotlin_version=1.13.12+kotlin.2.4.0
moulconfig_version=4.7.2
hypixel_mod_api_version=1.0.2